<?php

declare(strict_types=1);

namespace Tests\Support;

use PDO;
use RuntimeException;

/**
 * Schema and data management for the `recharge_test` database.
 *
 * The feature suite is black-box over HTTP, but the database behind the
 * test server must be deterministic:
 *
 *  - ensureSchema(): creates `recharge_test` (never `recharge_db`) and
 *    imports database/database.sql plus database/migration_*.sql when the
 *    schema is missing. The `CREATE DATABASE` / `USE` header lines of those
 *    files are stripped before execution, so no statement can ever retarget
 *    the dev database. Runs once per PHPUnit process (static guard).
 *  - truncateAll(): wipes every table of `recharge_test` (FK checks off),
 *    resetting AUTO_INCREMENT so seeded ids are stable (admin = 1, user = 2).
 *  - seed(): inserts the two known users with bcrypt hashes generated by the
 *    same password_hash() call the app uses, so User::login()'s
 *    password_verify() accepts them.
 */
final class Database
{
    /** The only database this class ever connects to (besides the server-level connection). */
    public const NAME = 'recharge_test';

    /** Tables the API relies on: base schema (database.sql) + migrations. */
    private const REQUIRED_TABLES = [
        'pedidos',
        'pagos',
        'users',
        'system_config',
        'juegos',
        'notificaciones',
        'password_resets',
        'productos',
        'payment_config',
    ];

    /** Columns added on top of database.sql by the migrations. */
    private const REQUIRED_COLUMNS = [
        ['table' => 'pedidos', 'column' => 'user_id'],
        ['table' => 'users', 'column' => 'avatar_url'],
    ];

    /**
     * Schema sources in application order. database/migration_fix_admin.sql is
     * intentionally excluded: it only upserts an admin row whose stored hash
     * matches no known password; seed() owns the user rows.
     */
    private const SCHEMA_SOURCES = [
        'database/database.sql',
        'database/migration_fix_user.sql',
        'database/migration_avatar.sql',
        'database/migration_juegos.sql',
        'database/migration_notifications.sql',
        'database/migration_password_resets.sql',
        'database/migration_productos.sql',
    ];

    private const DB_USER = 'root';
    private const DB_PASS = '';

    private static bool $ensured = false;

    /** Create the test database and import the schema once per process. */
    public static function ensureSchema(): void
    {
        if (self::$ensured) {
            return;
        }

        // Server-level connection (no selected database), as required by spec.
        $server = self::connect();
        $server->exec(
            'CREATE DATABASE IF NOT EXISTS `' . self::NAME . '`'
            . ' CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'
        );

        $db = self::connect(self::NAME);
        if (!self::schemaPresent($db)) {
            self::importSchema($db);
        }

        self::$ensured = true;
    }

    /** TRUNCATE every table of the test schema (resets AUTO_INCREMENT). */
    public static function truncateAll(): void
    {
        $db = self::connect(self::NAME);
        $db->exec('SET FOREIGN_KEY_CHECKS = 0');
        try {
            /** @var list<string> $tables */
            $tables = $db->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);
            foreach ($tables as $table) {
                $db->exec('TRUNCATE TABLE `' . $table . '`');
            }
        } finally {
            $db->exec('SET FOREIGN_KEY_CHECKS = 1');
        }
    }

    /** Insert the two users the feature tests log in as. */
    public static function seed(): void
    {
        $db = self::connect(self::NAME);
        $insert = $db->prepare(
            'INSERT INTO users (name, email, password, role) VALUES (?, ?, ?, ?)'
        );
        $insert->execute(['Administrator', 'admin@sisifo.store', self::hash('admin123'), 'admin']);
        $insert->execute(['Test User', 'test@test.com', self::hash('password123'), 'user']);
    }

    // ------------------------------------------------------------------
    // Internals
    // ------------------------------------------------------------------

    private static function connect(?string $database = null): PDO
    {
        $dsn = 'mysql:host=127.0.0.1;charset=utf8mb4'
            . ($database !== null ? ';dbname=' . $database : '');

        return new PDO($dsn, self::DB_USER, self::DB_PASS, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        ]);
    }

    private static function hash(string $plain): string
    {
        return password_hash($plain, PASSWORD_BCRYPT);
    }

    private static function schemaPresent(PDO $db): bool
    {
        $stmt = $db->prepare(
            'SELECT COUNT(*) FROM information_schema.TABLES
             WHERE TABLE_SCHEMA = :schema AND TABLE_NAME = :table'
        );
        foreach (self::REQUIRED_TABLES as $table) {
            $stmt->execute(['schema' => self::NAME, 'table' => $table]);
            if ((int) $stmt->fetchColumn() === 0) {
                return false;
            }
        }

        foreach (self::REQUIRED_COLUMNS as $column) {
            if (!self::columnExists($db, $column['table'], $column['column'])) {
                return false;
            }
        }

        return true;
    }

    private static function columnExists(PDO $db, string $table, string $column): bool
    {
        $stmt = $db->prepare(
            'SELECT COUNT(*) FROM information_schema.COLUMNS
             WHERE TABLE_SCHEMA = :schema AND TABLE_NAME = :table AND COLUMN_NAME = :column'
        );
        $stmt->execute(['schema' => self::NAME, 'table' => $table, 'column' => $column]);

        return (int) $stmt->fetchColumn() > 0;
    }

    /**
     * Apply every schema source to the test database.
     *
     * Statements are split on ';' after dropping full-line `--` comments and
     * any `CREATE DATABASE` / `USE` statement, so the only schema that can be
     * touched is `recharge_test` (the connection has it selected and the USE
     * lines never execute).
     */
    private static function importSchema(PDO $db): void
    {
        $root = dirname(__DIR__, 2);

        foreach (self::SCHEMA_SOURCES as $relativePath) {
            $path = $root . '/' . $relativePath;
            if (!is_file($path)) {
                throw new RuntimeException("Schema source not found: {$relativePath}");
            }

            $sql = (string) file_get_contents($path);
            $statements = self::statementsOf($sql);
            foreach ($statements as $statement) {
                // Migration ALTERs are only safe once; skip columns that
                // already exist so a partial schema can be re-imported.
                if (preg_match(
                    '/^\s*ALTER\s+TABLE\s+`?(\w+)`?\s+ADD\s+(?:COLUMN\s+)?`?(\w+)/i',
                    $statement,
                    $matches
                ) === 1 && self::columnExists($db, $matches[1], $matches[2])) {
                    continue;
                }

                $db->exec($statement);
            }
        }
    }

    /** @return list<string> */
    private static function statementsOf(string $sql): array
    {
        $kept = [];
        foreach (preg_split('/\R/', $sql) ?: [] as $line) {
            $trimmed = ltrim($line);
            if (str_starts_with($trimmed, '--')) {
                continue;
            }
            // Header lines that would retarget another database — stripped.
            if (preg_match('/^(CREATE\s+DATABASE|USE)\s/i', $trimmed) === 1) {
                continue;
            }
            $kept[] = $line;
        }

        $statements = [];
        foreach (explode(';', implode("\n", $kept)) as $statement) {
            $statement = trim($statement);
            if ($statement !== '') {
                $statements[] = $statement;
            }
        }

        return $statements;
    }
}
